apiVersion: v1
kind: Service
metadata:
  name: mongodb-server
  labels:
    name: mongodb-server
spec:
  ports:
    - port: 27017
      name: mongodb-server
  selector:
    name: mongodb-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb-server
        role: mongodb
    name: mongodb
    spec:
      volumes: 
      - name: data
        emptyDir: {}
      containers:
      - name: mongodb
        image: yijunlu/mongodb-alpine:v1
        ports:
          - containerPort: 27017
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
          - name: data
            mountPath: /datadir
