apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    name: mysql-server
spec:
  ports:
    - port: 3306
      name: mysql-server
  selector:
    name: mysql-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        role: mysql
    name: mysql
    spec:
      volumes: 
      - name: data
        emptyDir: {}
      containers:
      - name: mysql
        image: yijunlu/mysql-alpine:v4
        ports:
          - containerPort: 3306
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
          - name: data
            mountPath: /datadir
