apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  labels:
    name: nginx-server
spec:
  ports:
    - port: 80 
      name: nginx-80
    - port: 443
      name: nginx-443
  selector:
    name: nginx-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-server
        role: nginx
    name: nginx
    spec:
      volumes: 
      - name: data
        emptyDir: {}
      containers:
      - name: nginx
        image: yijunlu/nginx-alpine:v2
        ports:
          - containerPort: 80
          - containerPort: 443
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
          - name: data
            mountPath: /datadir
