apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    name: redis-server
spec:
  ports:
    - port: 6379
      name: redis-server
  selector:
    name: redis-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-server
        role: master
    name: redis-master
    spec:
      volumes: 
      - name: data
        emptyDir: {}
      containers:
      - name: master
        image: yijunlu/redis-single:v1
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
